name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #test: [paranoid, conf_options, client, basic, dual-proto, otp, iptables, revocation]
        test: [basic, client, conf_options, dual-proto, paranoid]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/sans-sroc/openvpn
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Run tests
        env:
          IMG: ${{ steps.meta.outputs.tags }}
          DEBUG: 1
        run: test/run.sh --test ${{ matrix.test }} ${{ steps.meta.outputs.tags }}
